{
  "build": "pyhd8ed1ab_0",
  "build_number": 0,
  "channel": "https://conda.anaconda.org/conda-forge/noarch",
  "constrains": [],
  "depends": [
    "cryptography >=3.4.0",
    "keyring",
    "pkce",
    "pydantic <2.0",
    "pyjwt",
    "python >=3.8",
    "python-dotenv",
    "requests"
  ],
  "extracted_package_dir": "C:\\Users\\sanme\\annaconda\\pkgs\\anaconda-cloud-auth-0.1.3-pyhd8ed1ab_0",
  "files": [
    "Lib/site-packages/anaconda_cloud_auth-0.1.3.dist-info/INSTALLER",
    "Lib/site-packages/anaconda_cloud_auth-0.1.3.dist-info/METADATA",
    "Lib/site-packages/anaconda_cloud_auth-0.1.3.dist-info/RECORD",
    "Lib/site-packages/anaconda_cloud_auth-0.1.3.dist-info/REQUESTED",
    "Lib/site-packages/anaconda_cloud_auth-0.1.3.dist-info/WHEEL",
    "Lib/site-packages/anaconda_cloud_auth-0.1.3.dist-info/direct_url.json",
    "Lib/site-packages/anaconda_cloud_auth-0.1.3.dist-info/licenses/LICENSE",
    "Lib/site-packages/anaconda_cloud_auth/__init__.py",
    "Lib/site-packages/anaconda_cloud_auth/_version.py",
    "Lib/site-packages/anaconda_cloud_auth/actions.py",
    "Lib/site-packages/anaconda_cloud_auth/cli.py",
    "Lib/site-packages/anaconda_cloud_auth/client.py",
    "Lib/site-packages/anaconda_cloud_auth/config.py",
    "Lib/site-packages/anaconda_cloud_auth/console.py",
    "Lib/site-packages/anaconda_cloud_auth/exceptions.py",
    "Lib/site-packages/anaconda_cloud_auth/handlers.py",
    "Lib/site-packages/anaconda_cloud_auth/jwt.py",
    "Lib/site-packages/anaconda_cloud_auth/py.typed",
    "Lib/site-packages/anaconda_cloud_auth/token.py",
    ".nonadmin",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/__init__.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/_version.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/actions.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/cli.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/client.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/config.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/console.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/exceptions.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/handlers.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/jwt.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/token.cpython-312.pyc"
  ],
  "fn": "anaconda-cloud-auth-0.1.3-pyhd8ed1ab_0.conda",
  "license": "BSD-3-Clause",
  "link": {
    "source": "C:\\Users\\sanme\\annaconda\\pkgs\\anaconda-cloud-auth-0.1.3-pyhd8ed1ab_0",
    "type": 1
  },
  "md5": "ae27975a75a80332a3669ed79b0ca78a",
  "name": "anaconda-cloud-auth",
  "noarch": "python",
  "package_tarball_full_path": "C:\\Users\\sanme\\annaconda\\pkgs\\anaconda-cloud-auth-0.1.3-pyhd8ed1ab_0.conda",
  "package_type": "noarch_python",
  "paths_data": {
    "paths": [
      {
        "_path": "site-packages/anaconda_cloud_auth-0.1.3.dist-info/INSTALLER",
        "path_type": "hardlink",
        "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "sha256_in_prefix": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "size_in_bytes": 5
      },
      {
        "_path": "site-packages/anaconda_cloud_auth-0.1.3.dist-info/METADATA",
        "path_type": "hardlink",
        "sha256": "ed00ad9e4e2b0e6979e28c3a9c8c49f362a67e3faf1eff7d30f1e2fa8382c2f9",
        "sha256_in_prefix": "ed00ad9e4e2b0e6979e28c3a9c8c49f362a67e3faf1eff7d30f1e2fa8382c2f9",
        "size_in_bytes": 5871
      },
      {
        "_path": "site-packages/anaconda_cloud_auth-0.1.3.dist-info/RECORD",
        "path_type": "hardlink",
        "sha256": "b747392907d66a6271347e68a5e1b3d1fe2368144e68d686c81bfc7811bf1e30",
        "sha256_in_prefix": "b747392907d66a6271347e68a5e1b3d1fe2368144e68d686c81bfc7811bf1e30",
        "size_in_bytes": 2345
      },
      {
        "_path": "site-packages/anaconda_cloud_auth-0.1.3.dist-info/REQUESTED",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      },
      {
        "_path": "site-packages/anaconda_cloud_auth-0.1.3.dist-info/WHEEL",
        "path_type": "hardlink",
        "sha256": "f5006e1e183a14d5bb969a5ba05daf2956c2193573b05ca48114238e56a3ae10",
        "sha256_in_prefix": "f5006e1e183a14d5bb969a5ba05daf2956c2193573b05ca48114238e56a3ae10",
        "size_in_bytes": 87
      },
      {
        "_path": "site-packages/anaconda_cloud_auth-0.1.3.dist-info/direct_url.json",
        "path_type": "hardlink",
        "sha256": "53b77cb5af9f4b6d60413aa683d970f2c844b5ed6cf8da3b43dc0cd275893d93",
        "sha256_in_prefix": "53b77cb5af9f4b6d60413aa683d970f2c844b5ed6cf8da3b43dc0cd275893d93",
        "size_in_bytes": 115
      },
      {
        "_path": "site-packages/anaconda_cloud_auth-0.1.3.dist-info/licenses/LICENSE",
        "path_type": "hardlink",
        "sha256": "8372f6c92cbeb44c769041fd46cdaf12946c48743ed714c29059b0d917626cb8",
        "sha256_in_prefix": "8372f6c92cbeb44c769041fd46cdaf12946c48743ed714c29059b0d917626cb8",
        "size_in_bytes": 1544
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/__init__.py",
        "path_type": "hardlink",
        "sha256": "cc28c86f9eb98fc5605de1af80e36af7c4b8685e97349374a63c9d55200135cf",
        "sha256_in_prefix": "cc28c86f9eb98fc5605de1af80e36af7c4b8685e97349374a63c9d55200135cf",
        "size_in_bytes": 394
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/_version.py",
        "path_type": "hardlink",
        "sha256": "0986d97d963bc7f17e539f9d177f9e4af72c204b7e3da357b341570622e45c44",
        "sha256_in_prefix": "0986d97d963bc7f17e539f9d177f9e4af72c204b7e3da357b341570622e45c44",
        "size_in_bytes": 160
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/actions.py",
        "path_type": "hardlink",
        "sha256": "30411bf61380ff65f8960b7df6c479b9720674a97346f008668def159cab0127",
        "sha256_in_prefix": "30411bf61380ff65f8960b7df6c479b9720674a97346f008668def159cab0127",
        "size_in_bytes": 8777
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/cli.py",
        "path_type": "hardlink",
        "sha256": "f27091925ba9a0a4c4d8ecf6670ef16177a56cd492bd7720dd25c411f0703c8b",
        "sha256_in_prefix": "f27091925ba9a0a4c4d8ecf6670ef16177a56cd492bd7720dd25c411f0703c8b",
        "size_in_bytes": 458
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/client.py",
        "path_type": "hardlink",
        "sha256": "8c978db4c17bab5bd05c62ca675d073cb2e9d01b498810031322856dc58e5acc",
        "sha256_in_prefix": "8c978db4c17bab5bd05c62ca675d073cb2e9d01b498810031322856dc58e5acc",
        "size_in_bytes": 2661
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/config.py",
        "path_type": "hardlink",
        "sha256": "7ae21497b45efa11c4b6e9bd5a1ebb2f81f361dd019eba75c840fb9922461eef",
        "sha256_in_prefix": "7ae21497b45efa11c4b6e9bd5a1ebb2f81f361dd019eba75c840fb9922461eef",
        "size_in_bytes": 2207
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/console.py",
        "path_type": "hardlink",
        "sha256": "5fb293ce7ee613ac1699216ec8852e51ab9cef333826de1803943e750d19ceb4",
        "sha256_in_prefix": "5fb293ce7ee613ac1699216ec8852e51ab9cef333826de1803943e750d19ceb4",
        "size_in_bytes": 868
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/exceptions.py",
        "path_type": "hardlink",
        "sha256": "e054b868d94d4cf3cb437e463dff1a8b41fb5e2573a174fa54ecf9a9f09f33e9",
        "sha256_in_prefix": "e054b868d94d4cf3cb437e463dff1a8b41fb5e2573a174fa54ecf9a9f09f33e9",
        "size_in_bytes": 247
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/handlers.py",
        "path_type": "hardlink",
        "sha256": "4953f5409cccb53cbf2bf5d95b49072d1b371b606f6622f0e3de247fab3a8f43",
        "sha256_in_prefix": "4953f5409cccb53cbf2bf5d95b49072d1b371b606f6622f0e3de247fab3a8f43",
        "size_in_bytes": 5012
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/jwt.py",
        "path_type": "hardlink",
        "sha256": "378853786792a647b789ceb17ab28d1227a764b032681ea36418ebb5e9ef6623",
        "sha256_in_prefix": "378853786792a647b789ceb17ab28d1227a764b032681ea36418ebb5e9ef6623",
        "size_in_bytes": 883
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/py.typed",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      },
      {
        "_path": "site-packages/anaconda_cloud_auth/token.py",
        "path_type": "hardlink",
        "sha256": "4f28dc985d22b82669a186835eddfd51c91dbf8e1817ba648dffe6ca75111173",
        "sha256_in_prefix": "4f28dc985d22b82669a186835eddfd51c91dbf8e1817ba648dffe6ca75111173",
        "size_in_bytes": 7730
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/__init__.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/_version.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/actions.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/cli.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/client.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/config.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/console.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/exceptions.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/handlers.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/jwt.cpython-312.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "Lib/site-packages/anaconda_cloud_auth/__pycache__/token.cpython-312.pyc",
        "path_type": "pyc_file"
      }
    ],
    "paths_version": 1
  },
  "requested_spec": "None",
  "sha256": "de0fe86d28482786a5e06187263d4a9452aee8af54451c893d10a2ed24eadab1",
  "size": 19158,
  "subdir": "noarch",
  "timestamp": 1694440579000,
  "url": "https://conda.anaconda.org/conda-forge/noarch/anaconda-cloud-auth-0.1.3-pyhd8ed1ab_0.conda",
  "version": "0.1.3"
}